monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    handlers:
        api_user_log:
            type: rotating_file
            max_files: 90
            level: debug
            path: '%kernel.logs_dir%/api/%kernel.environment%.log'
            channels: api_user_log
